import type { NextPage } from "next";
import Head from "next/head";
import NumericodeDecoder from "../components/NumericodeDecoder/NumericodeDecoder";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Numericode Processor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NumericodeDecoder />

    </div>
  );
};

export default Home;
